repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.8
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]

- repo: local
  hooks:
    - id: pyright
      name: pyright
      entry: pyright
      language: system
      types: [python]
      pass_filenames: false

- repo: local
  hooks:
    - id: pytest
      name: Run Pytest
      entry: pytest tests
      language: system
      types: [python]
      pass_filenames: false
      stages: [pre-push]
