# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
    python: python3.12

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.2
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format

# This repository provides the `python_uv` language definition.
-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.13
    hooks:
    -   id: uv-lock

# Local hooks use `language: python` so pre-commit creates virtual
# environments and installs the required tooling automatically.
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        additional_dependencies:
        -   mypy==1.10.0
        # Type stubs required for linting utility scripts
        -   types-requests
        -   types-beautifulsoup4
    -   id: pytest
        name: pytest
        entry: pytest
        language: python
        types: [python]
        pass_filenames: false
        additional_dependencies:
        # Install project and test dependencies so the hook can run in isolation
        -   pytest==8.4.1
        -   pytest-asyncio
        -   pytest-mock
        -   pytest-cov
        -   beautifulsoup4
        -   lxml
        -   flask
        -   python-telegram-bot
        -   wikipedia
        -   libtorrent
        -   plexapi
        -   thefuzz
        -   "httpx[http2]"
