site_name: "1337x"
base_url: "https://1337x.to"
search_path: "/search/{query}/1/"
selectors:
  results_container: "tbody tr"
  title: "td a:nth-of-type(2)"
  details_page_link: "td a:nth-of-type(2)"
  seeders: "td:nth-of-type(2)"
  leechers: "td:nth-of-type(3)"
  size: "td:nth-of-type(5)"
  uploader: "td:nth-of-type(6) a"
  magnet_link: null
details_page_selectors:
  magnet_link: "a[href^='magnet:']"
